### PR TITLE
Update Hallowuino.ino

### PR DESCRIPTION
**Pull request by ghost**
Code refactoring.

### CODE REVIEW

**Comment by ghost** [comment]
Are you debouncing buttonPin in hardware?  I don't see the schematic on here.

Thanks,
MinutesToMidnight

**Comment by ghost** [comment]
Reduced RAM footprint by ~50%, by placing strings in the flash macro F().

**Review by hevnsnt — APPROVED** [review]

**Comment by hevnsnt** [comment]
Re: Pull up -- Not doing it in hardware, good catch.  We will need to set this in software.

**Comment by ghost** [comment]
Cool, I'm glad to help.  I can debounce it in software then too. Does a
button press pull it to ground? BTW thanks for the ESP Dev board.  --wheel
chair guy

**Pull request merged**
